# Inserts a blank line between shell prompts
add_newline = true

# Timeout for file scan (milliseconds)
scan_timeout = 30

[directory]
truncation_length = 10
truncation_symbol = "…/"

[time]
disabled = false
time_format = "%F %T"
